/*
 * ucd_clkup_v1_api
 * Swagger documentation for UCD Customer Lookup Service API
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.customerlookup;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

/**
 * AccountKey
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T20:02:06.369160100+05:30[Asia/Calcutta]")
public class AccountKey {
  public static final String SERIALIZED_NAME_ACCOUNT_TYPE_ID = "accountTypeId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE_ID)
  private Integer accountTypeId;

  public static final String SERIALIZED_NAME_ACCOUNT_KEY = "accountKey";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_KEY)
  private String accountKey;

  public AccountKey() {
  }

  public AccountKey accountTypeId(Integer accountTypeId) {
    
    this.accountTypeId = accountTypeId;
    return this;
  }

   /**
   * Account Type ID values  * 0 - WU COM INTL R3 Nordic * 1 - WUCOM R3 Nordic * 2 - WUGOLD  * 3 - Loyalty  * 4 - TMT  * 5 - Prepaid Cardholder I2C  * 6 - Prepaid Cardholder FIS * 7 - Prepaid Purchaser  * 8 - MTX  * 9 - WUBS  * 10 - R2/R3/R4 SmartPhone  * 11 - R2/R3/R4 Web  * 12 - Banking * 13 - Guest US * 14 - Wallet * 15 - Correction Pay * 16 - Crypto * 17 - Guest EU * 99 - OtherAccountTypeID 
   * @return accountTypeId
  **/
  @javax.annotation.Nonnull
  public Integer getAccountTypeId() {
    return accountTypeId;
  }


  public void setAccountTypeId(Integer accountTypeId) {
    this.accountTypeId = accountTypeId;
  }


  public AccountKey accountKey(String accountKey) {
    
    this.accountKey = accountKey;
    return this;
  }

   /**
   * Unique identifier for Accounts within the application.
   * @return accountKey
  **/
  @javax.annotation.Nonnull
  public String getAccountKey() {
    return accountKey;
  }


  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountKey accountKey = (AccountKey) o;
    return Objects.equals(this.accountTypeId, accountKey.accountTypeId) &&
        Objects.equals(this.accountKey, accountKey.accountKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountTypeId, accountKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountKey {\n");
    sb.append("    accountTypeId: ").append(toIndentedString(accountTypeId)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountTypeId");
    openapiFields.add("accountKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accountTypeId");
    openapiRequiredFields.add("accountKey");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AccountKey
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AccountKey.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccountKey is not found in the empty JSON string", AccountKey.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AccountKey.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AccountKey` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AccountKey.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("accountKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccountKey.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccountKey' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccountKey> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccountKey.class));

       return (TypeAdapter<T>) new TypeAdapter<AccountKey>() {
           @Override
           public void write(JsonWriter out, AccountKey value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AccountKey read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AccountKey given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AccountKey
  * @throws IOException if the JSON string is invalid with respect to AccountKey
  */
  public static AccountKey fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccountKey.class);
  }

 /**
  * Convert an instance of AccountKey to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

