/*
 * ucd_cregn_v1_api
 * Swagger documentation for UCD Customer Registration Service API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.customerregistration;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.wu.brwallet.customer.profile.model.common.ucd.customerregistration.JSON;

/**
 * Customer Counter Party Link Details
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T20:58:59.701576900+05:30[Asia/Calcutta]")
public class CounterPartyLink {
  public static final String SERIALIZED_NAME_COUNTER_PARTY_UMN = "counterPartyUmn";
  @SerializedName(SERIALIZED_NAME_COUNTER_PARTY_UMN)
  private String counterPartyUmn;

  public static final String SERIALIZED_NAME_COUNTER_PARTY_GID = "counterPartyGid";
  @SerializedName(SERIALIZED_NAME_COUNTER_PARTY_GID)
  private String counterPartyGid;

  public static final String SERIALIZED_NAME_CUSTOMER_ROLE = "customerRole";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ROLE)
  private Integer customerRole;

  public CounterPartyLink() {
  }

  public CounterPartyLink counterPartyUmn(String counterPartyUmn) {
    
    this.counterPartyUmn = counterPartyUmn;
    return this;
  }

   /**
   * Universal Membership Number. Not required as part of the customer registration request.
   * @return counterPartyUmn
  **/
  @javax.annotation.Nullable
  public String getCounterPartyUmn() {
    return counterPartyUmn;
  }


  public void setCounterPartyUmn(String counterPartyUmn) {
    this.counterPartyUmn = counterPartyUmn;
  }


  public CounterPartyLink counterPartyGid(String counterPartyGid) {
    
    this.counterPartyGid = counterPartyGid;
    return this;
  }

   /**
   * Galactic ID generated by EAS system. It is used by Compliance system to find unique customer.
   * @return counterPartyGid
  **/
  @javax.annotation.Nullable
  public String getCounterPartyGid() {
    return counterPartyGid;
  }


  public void setCounterPartyGid(String counterPartyGid) {
    this.counterPartyGid = counterPartyGid;
  }


  public CounterPartyLink customerRole(Integer customerRole) {
    
    this.customerRole = customerRole;
    return this;
  }

   /**
   * Customer Role Types * 1 - SENDER * 2 - RECEIVER * 3 - SENDER AND RECEIVER 
   * @return customerRole
  **/
  @javax.annotation.Nullable
  public Integer getCustomerRole() {
    return customerRole;
  }


  public void setCustomerRole(Integer customerRole) {
    this.customerRole = customerRole;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CounterPartyLink counterPartyLink = (CounterPartyLink) o;
    return Objects.equals(this.counterPartyUmn, counterPartyLink.counterPartyUmn) &&
        Objects.equals(this.counterPartyGid, counterPartyLink.counterPartyGid) &&
        Objects.equals(this.customerRole, counterPartyLink.customerRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(counterPartyUmn, counterPartyGid, customerRole);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CounterPartyLink {\n");
    sb.append("    counterPartyUmn: ").append(toIndentedString(counterPartyUmn)).append("\n");
    sb.append("    counterPartyGid: ").append(toIndentedString(counterPartyGid)).append("\n");
    sb.append("    customerRole: ").append(toIndentedString(customerRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("counterPartyUmn");
    openapiFields.add("counterPartyGid");
    openapiFields.add("customerRole");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CounterPartyLink
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CounterPartyLink.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CounterPartyLink is not found in the empty JSON string", CounterPartyLink.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CounterPartyLink.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CounterPartyLink` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("counterPartyUmn") != null && !jsonObj.get("counterPartyUmn").isJsonNull()) && !jsonObj.get("counterPartyUmn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `counterPartyUmn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("counterPartyUmn").toString()));
      }
      if ((jsonObj.get("counterPartyGid") != null && !jsonObj.get("counterPartyGid").isJsonNull()) && !jsonObj.get("counterPartyGid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `counterPartyGid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("counterPartyGid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CounterPartyLink.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CounterPartyLink' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CounterPartyLink> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CounterPartyLink.class));

       return (TypeAdapter<T>) new TypeAdapter<CounterPartyLink>() {
           @Override
           public void write(JsonWriter out, CounterPartyLink value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CounterPartyLink read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CounterPartyLink given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CounterPartyLink
  * @throws IOException if the JSON string is invalid with respect to CounterPartyLink
  */
  public static CounterPartyLink fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CounterPartyLink.class);
  }

 /**
  * Convert an instance of CounterPartyLink to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

