/*
 * ucd_clkup_v1_api
 * Swagger documentation for UCD Customer Lookup Service API
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.customerlookup;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

/**
 * This is the request model for CustomerLookupByGalacticId service. This is to search for a customer by Galactic Id/PCP Number (which will resolve to Galactic Id) and receive the UCD profile of the customer found.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T20:02:06.369160100+05:30[Asia/Calcutta]")
public class CustomerLookupByGalacticIdRequest {
  public static final String SERIALIZED_NAME_HEADER = "header";
  @SerializedName(SERIALIZED_NAME_HEADER)
  private Header header;

  public static final String SERIALIZED_NAME_LOOKUP_TYPE = "lookupType";
  @SerializedName(SERIALIZED_NAME_LOOKUP_TYPE)
  private String lookupType;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private GalacticIdKey key;

  /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return history details for ProfileComplianceSumary, CustomerKYCDetails &amp; CustomerVerificationDetails. If the flag value is &#39;N&#39; then will return not return history for ProfileComplianceSumary, CustomerKYCDetails &amp; CustomerVerificationDetails.
   */
  @JsonAdapter(IncludeHistoryDetailsEnum.Adapter.class)
  public enum IncludeHistoryDetailsEnum {
    Y("Y"),
    
    N("N");

    private String value;

    IncludeHistoryDetailsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IncludeHistoryDetailsEnum fromValue(String value) {
      for (IncludeHistoryDetailsEnum b : IncludeHistoryDetailsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IncludeHistoryDetailsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IncludeHistoryDetailsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IncludeHistoryDetailsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IncludeHistoryDetailsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_INCLUDE_HISTORY_DETAILS = "includeHistoryDetails";
  @SerializedName(SERIALIZED_NAME_INCLUDE_HISTORY_DETAILS)
  private IncludeHistoryDetailsEnum includeHistoryDetails = IncludeHistoryDetailsEnum.N;

  /**
   * Flag which indicates to/not to convert the Special Characters to ASCII for Sender &amp; Receiver details (Name, Address, Address in UAB). For Loyalty, this flag will be defaulted to Y. * If not passed in the request, as is values will be returned in response by default. * If passed as N in the request, as is values will be returned in response. * If passed as Y in the request, the Special Characters will be converted to ASCII and will be returned in response. 
   */
  @JsonAdapter(EnableTransliterationFlagEnum.Adapter.class)
  public enum EnableTransliterationFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    EnableTransliterationFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EnableTransliterationFlagEnum fromValue(String value) {
      for (EnableTransliterationFlagEnum b : EnableTransliterationFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EnableTransliterationFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EnableTransliterationFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EnableTransliterationFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EnableTransliterationFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ENABLE_TRANSLITERATION_FLAG = "enableTransliterationFlag";
  @SerializedName(SERIALIZED_NAME_ENABLE_TRANSLITERATION_FLAG)
  private EnableTransliterationFlagEnum enableTransliterationFlag = EnableTransliterationFlagEnum.N;

  /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return additional funding sources (like funding sources added by TMT), if any, along with funding sources added by other than TMT. If the flag value is &#39;N&#39; then will return Funding Sources which are added by other than TMT.
   */
  @JsonAdapter(SendAllFundSrcEnum.Adapter.class)
  public enum SendAllFundSrcEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendAllFundSrcEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendAllFundSrcEnum fromValue(String value) {
      for (SendAllFundSrcEnum b : SendAllFundSrcEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendAllFundSrcEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendAllFundSrcEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendAllFundSrcEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendAllFundSrcEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_ALL_FUND_SRC = "sendAllFundSrc";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_FUND_SRC)
  private SendAllFundSrcEnum sendAllFundSrc = SendAllFundSrcEnum.N;

  /**
   * If available, PhoneVvStatus - N / L / M / P will be returned in response by default. PhoneVvStatus - Z / T / R / S / V / A / B / U / C / D will only be returned if this field is send as Y in the request.
   */
  @JsonAdapter(SendAllPhoneVvStatusEnum.Adapter.class)
  public enum SendAllPhoneVvStatusEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendAllPhoneVvStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendAllPhoneVvStatusEnum fromValue(String value) {
      for (SendAllPhoneVvStatusEnum b : SendAllPhoneVvStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendAllPhoneVvStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendAllPhoneVvStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendAllPhoneVvStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendAllPhoneVvStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_ALL_PHONE_VV_STATUS = "sendAllPhoneVvStatus";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_PHONE_VV_STATUS)
  private SendAllPhoneVvStatusEnum sendAllPhoneVvStatus = SendAllPhoneVvStatusEnum.N;

  /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return Receiver details. If the flag value is &#39;N&#39; then will return not return Receiver details.
   */
  @JsonAdapter(IncludeReceiverDetailsEnum.Adapter.class)
  public enum IncludeReceiverDetailsEnum {
    Y("Y"),
    
    N("N");

    private String value;

    IncludeReceiverDetailsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IncludeReceiverDetailsEnum fromValue(String value) {
      for (IncludeReceiverDetailsEnum b : IncludeReceiverDetailsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IncludeReceiverDetailsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IncludeReceiverDetailsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IncludeReceiverDetailsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IncludeReceiverDetailsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_INCLUDE_RECEIVER_DETAILS = "includeReceiverDetails";
  @SerializedName(SERIALIZED_NAME_INCLUDE_RECEIVER_DETAILS)
  private IncludeReceiverDetailsEnum includeReceiverDetails = IncludeReceiverDetailsEnum.N;

  /**
   * This flag would indicate to include consolidated funding sources from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return funding sources from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated funding sources from both primary &amp; scondary profiles. 
   */
  @JsonAdapter(SendConsolidatedFundingSourcesEnum.Adapter.class)
  public enum SendConsolidatedFundingSourcesEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendConsolidatedFundingSourcesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendConsolidatedFundingSourcesEnum fromValue(String value) {
      for (SendConsolidatedFundingSourcesEnum b : SendConsolidatedFundingSourcesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendConsolidatedFundingSourcesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendConsolidatedFundingSourcesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendConsolidatedFundingSourcesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendConsolidatedFundingSourcesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_CONSOLIDATED_FUNDING_SOURCES = "sendConsolidatedFundingSources";
  @SerializedName(SERIALIZED_NAME_SEND_CONSOLIDATED_FUNDING_SOURCES)
  private SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources = SendConsolidatedFundingSourcesEnum.N;

  /**
   * If includeReceiverDetails is sent as Y then this flag would indicate to include consolidated receviers in the primary profile from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return receviers on their respective profile.   * If the flag value is &#39;Y&#39;, then web service will return consolidated receivers in the primary profile from both primary &amp; scondary profiles. 
   */
  @JsonAdapter(SendConsolidatedReceiversEnum.Adapter.class)
  public enum SendConsolidatedReceiversEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendConsolidatedReceiversEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendConsolidatedReceiversEnum fromValue(String value) {
      for (SendConsolidatedReceiversEnum b : SendConsolidatedReceiversEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendConsolidatedReceiversEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendConsolidatedReceiversEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendConsolidatedReceiversEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendConsolidatedReceiversEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_CONSOLIDATED_RECEIVERS = "sendConsolidatedReceivers";
  @SerializedName(SERIALIZED_NAME_SEND_CONSOLIDATED_RECEIVERS)
  private SendConsolidatedReceiversEnum sendConsolidatedReceivers = SendConsolidatedReceiversEnum.N;

  public static final String SERIALIZED_NAME_REQUEST_INITIATED_BY = "requestInitiatedBy";
  @SerializedName(SERIALIZED_NAME_REQUEST_INITIATED_BY)
  private String requestInitiatedBy;

  public CustomerLookupByGalacticIdRequest() {
  }

  public CustomerLookupByGalacticIdRequest header(Header header) {
    
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @javax.annotation.Nonnull
  public Header getHeader() {
    return header;
  }


  public void setHeader(Header header) {
    this.header = header;
  }


  public CustomerLookupByGalacticIdRequest lookupType(String lookupType) {
    
    this.lookupType = lookupType;
    return this;
  }

   /**
   * Indicates elements to be considered for lookup Indicates AND/OR condition for the lookup elements Currently this operation supports below combination -   1. Galactic Id       * Value to be passed in this element is GID.       * When lookupType &#x3D; GID, galacticId element is mandatory.   2. Customer Umn       * Value to be passed in this is UMN.       * When lookupType &#x3D; UMN, customerUmn element is mandatory.   3. Bank Profile Id       * Value to be passed in this is BPI.       * When lookupType &#x3D; BPI, bankProfileId element is mandatory.   4. Name AND Id Number       * Value to be passed in this element for Name AND Id Number combination is NMID.       * When lookupType &#x3D; NMID, name and idNumber elements are mandatory.   5. Dob AND Id Number       * Value to be passed in this element for Dob AND Id Number combination is DBID.       * When lookupType &#x3D; DBID, dob and idNumber elements are mandatory. 
   * @return lookupType
  **/
  @javax.annotation.Nullable
  public String getLookupType() {
    return lookupType;
  }


  public void setLookupType(String lookupType) {
    this.lookupType = lookupType;
  }


  public CustomerLookupByGalacticIdRequest key(GalacticIdKey key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nonnull
  public GalacticIdKey getKey() {
    return key;
  }


  public void setKey(GalacticIdKey key) {
    this.key = key;
  }


  public CustomerLookupByGalacticIdRequest includeHistoryDetails(IncludeHistoryDetailsEnum includeHistoryDetails) {
    
    this.includeHistoryDetails = includeHistoryDetails;
    return this;
  }

   /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return history details for ProfileComplianceSumary, CustomerKYCDetails &amp; CustomerVerificationDetails. If the flag value is &#39;N&#39; then will return not return history for ProfileComplianceSumary, CustomerKYCDetails &amp; CustomerVerificationDetails.
   * @return includeHistoryDetails
  **/
  @javax.annotation.Nullable
  public IncludeHistoryDetailsEnum getIncludeHistoryDetails() {
    return includeHistoryDetails;
  }


  public void setIncludeHistoryDetails(IncludeHistoryDetailsEnum includeHistoryDetails) {
    this.includeHistoryDetails = includeHistoryDetails;
  }


  public CustomerLookupByGalacticIdRequest enableTransliterationFlag(EnableTransliterationFlagEnum enableTransliterationFlag) {
    
    this.enableTransliterationFlag = enableTransliterationFlag;
    return this;
  }

   /**
   * Flag which indicates to/not to convert the Special Characters to ASCII for Sender &amp; Receiver details (Name, Address, Address in UAB). For Loyalty, this flag will be defaulted to Y. * If not passed in the request, as is values will be returned in response by default. * If passed as N in the request, as is values will be returned in response. * If passed as Y in the request, the Special Characters will be converted to ASCII and will be returned in response. 
   * @return enableTransliterationFlag
  **/
  @javax.annotation.Nullable
  public EnableTransliterationFlagEnum getEnableTransliterationFlag() {
    return enableTransliterationFlag;
  }


  public void setEnableTransliterationFlag(EnableTransliterationFlagEnum enableTransliterationFlag) {
    this.enableTransliterationFlag = enableTransliterationFlag;
  }


  public CustomerLookupByGalacticIdRequest sendAllFundSrc(SendAllFundSrcEnum sendAllFundSrc) {
    
    this.sendAllFundSrc = sendAllFundSrc;
    return this;
  }

   /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return additional funding sources (like funding sources added by TMT), if any, along with funding sources added by other than TMT. If the flag value is &#39;N&#39; then will return Funding Sources which are added by other than TMT.
   * @return sendAllFundSrc
  **/
  @javax.annotation.Nullable
  public SendAllFundSrcEnum getSendAllFundSrc() {
    return sendAllFundSrc;
  }


  public void setSendAllFundSrc(SendAllFundSrcEnum sendAllFundSrc) {
    this.sendAllFundSrc = sendAllFundSrc;
  }


  public CustomerLookupByGalacticIdRequest sendAllPhoneVvStatus(SendAllPhoneVvStatusEnum sendAllPhoneVvStatus) {
    
    this.sendAllPhoneVvStatus = sendAllPhoneVvStatus;
    return this;
  }

   /**
   * If available, PhoneVvStatus - N / L / M / P will be returned in response by default. PhoneVvStatus - Z / T / R / S / V / A / B / U / C / D will only be returned if this field is send as Y in the request.
   * @return sendAllPhoneVvStatus
  **/
  @javax.annotation.Nullable
  public SendAllPhoneVvStatusEnum getSendAllPhoneVvStatus() {
    return sendAllPhoneVvStatus;
  }


  public void setSendAllPhoneVvStatus(SendAllPhoneVvStatusEnum sendAllPhoneVvStatus) {
    this.sendAllPhoneVvStatus = sendAllPhoneVvStatus;
  }


  public CustomerLookupByGalacticIdRequest includeReceiverDetails(IncludeReceiverDetailsEnum includeReceiverDetails) {
    
    this.includeReceiverDetails = includeReceiverDetails;
    return this;
  }

   /**
   * If this flag is not sent then by default it is considered as N If the flag value is &#39;Y&#39;, then will return Receiver details. If the flag value is &#39;N&#39; then will return not return Receiver details.
   * @return includeReceiverDetails
  **/
  @javax.annotation.Nullable
  public IncludeReceiverDetailsEnum getIncludeReceiverDetails() {
    return includeReceiverDetails;
  }


  public void setIncludeReceiverDetails(IncludeReceiverDetailsEnum includeReceiverDetails) {
    this.includeReceiverDetails = includeReceiverDetails;
  }


  public CustomerLookupByGalacticIdRequest sendConsolidatedFundingSources(SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources) {
    
    this.sendConsolidatedFundingSources = sendConsolidatedFundingSources;
    return this;
  }

   /**
   * This flag would indicate to include consolidated funding sources from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return funding sources from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated funding sources from both primary &amp; scondary profiles. 
   * @return sendConsolidatedFundingSources
  **/
  @javax.annotation.Nullable
  public SendConsolidatedFundingSourcesEnum getSendConsolidatedFundingSources() {
    return sendConsolidatedFundingSources;
  }


  public void setSendConsolidatedFundingSources(SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources) {
    this.sendConsolidatedFundingSources = sendConsolidatedFundingSources;
  }


  public CustomerLookupByGalacticIdRequest sendConsolidatedReceivers(SendConsolidatedReceiversEnum sendConsolidatedReceivers) {
    
    this.sendConsolidatedReceivers = sendConsolidatedReceivers;
    return this;
  }

   /**
   * If includeReceiverDetails is sent as Y then this flag would indicate to include consolidated receviers in the primary profile from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return receviers on their respective profile.   * If the flag value is &#39;Y&#39;, then web service will return consolidated receivers in the primary profile from both primary &amp; scondary profiles. 
   * @return sendConsolidatedReceivers
  **/
  @javax.annotation.Nullable
  public SendConsolidatedReceiversEnum getSendConsolidatedReceivers() {
    return sendConsolidatedReceivers;
  }


  public void setSendConsolidatedReceivers(SendConsolidatedReceiversEnum sendConsolidatedReceivers) {
    this.sendConsolidatedReceivers = sendConsolidatedReceivers;
  }


  public CustomerLookupByGalacticIdRequest requestInitiatedBy(String requestInitiatedBy) {
    
    this.requestInitiatedBy = requestInitiatedBy;
    return this;
  }

   /**
   * To identify who has initiated the request.
   * @return requestInitiatedBy
  **/
  @javax.annotation.Nonnull
  public String getRequestInitiatedBy() {
    return requestInitiatedBy;
  }


  public void setRequestInitiatedBy(String requestInitiatedBy) {
    this.requestInitiatedBy = requestInitiatedBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerLookupByGalacticIdRequest customerLookupByGalacticIdRequest = (CustomerLookupByGalacticIdRequest) o;
    return Objects.equals(this.header, customerLookupByGalacticIdRequest.header) &&
        Objects.equals(this.lookupType, customerLookupByGalacticIdRequest.lookupType) &&
        Objects.equals(this.key, customerLookupByGalacticIdRequest.key) &&
        Objects.equals(this.includeHistoryDetails, customerLookupByGalacticIdRequest.includeHistoryDetails) &&
        Objects.equals(this.enableTransliterationFlag, customerLookupByGalacticIdRequest.enableTransliterationFlag) &&
        Objects.equals(this.sendAllFundSrc, customerLookupByGalacticIdRequest.sendAllFundSrc) &&
        Objects.equals(this.sendAllPhoneVvStatus, customerLookupByGalacticIdRequest.sendAllPhoneVvStatus) &&
        Objects.equals(this.includeReceiverDetails, customerLookupByGalacticIdRequest.includeReceiverDetails) &&
        Objects.equals(this.sendConsolidatedFundingSources, customerLookupByGalacticIdRequest.sendConsolidatedFundingSources) &&
        Objects.equals(this.sendConsolidatedReceivers, customerLookupByGalacticIdRequest.sendConsolidatedReceivers) &&
        Objects.equals(this.requestInitiatedBy, customerLookupByGalacticIdRequest.requestInitiatedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, lookupType, key, includeHistoryDetails, enableTransliterationFlag, sendAllFundSrc, sendAllPhoneVvStatus, includeReceiverDetails, sendConsolidatedFundingSources, sendConsolidatedReceivers, requestInitiatedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerLookupByGalacticIdRequest {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    lookupType: ").append(toIndentedString(lookupType)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    includeHistoryDetails: ").append(toIndentedString(includeHistoryDetails)).append("\n");
    sb.append("    enableTransliterationFlag: ").append(toIndentedString(enableTransliterationFlag)).append("\n");
    sb.append("    sendAllFundSrc: ").append(toIndentedString(sendAllFundSrc)).append("\n");
    sb.append("    sendAllPhoneVvStatus: ").append(toIndentedString(sendAllPhoneVvStatus)).append("\n");
    sb.append("    includeReceiverDetails: ").append(toIndentedString(includeReceiverDetails)).append("\n");
    sb.append("    sendConsolidatedFundingSources: ").append(toIndentedString(sendConsolidatedFundingSources)).append("\n");
    sb.append("    sendConsolidatedReceivers: ").append(toIndentedString(sendConsolidatedReceivers)).append("\n");
    sb.append("    requestInitiatedBy: ").append(toIndentedString(requestInitiatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("header");
    openapiFields.add("lookupType");
    openapiFields.add("key");
    openapiFields.add("includeHistoryDetails");
    openapiFields.add("enableTransliterationFlag");
    openapiFields.add("sendAllFundSrc");
    openapiFields.add("sendAllPhoneVvStatus");
    openapiFields.add("includeReceiverDetails");
    openapiFields.add("sendConsolidatedFundingSources");
    openapiFields.add("sendConsolidatedReceivers");
    openapiFields.add("requestInitiatedBy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("header");
    openapiRequiredFields.add("key");
    openapiRequiredFields.add("requestInitiatedBy");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CustomerLookupByGalacticIdRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CustomerLookupByGalacticIdRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomerLookupByGalacticIdRequest is not found in the empty JSON string", CustomerLookupByGalacticIdRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CustomerLookupByGalacticIdRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomerLookupByGalacticIdRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomerLookupByGalacticIdRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `header`
      Header.validateJsonObject(jsonObj.getAsJsonObject("header"));
      if ((jsonObj.get("lookupType") != null && !jsonObj.get("lookupType").isJsonNull()) && !jsonObj.get("lookupType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lookupType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lookupType").toString()));
      }
      // validate the required field `key`
      GalacticIdKey.validateJsonObject(jsonObj.getAsJsonObject("key"));
      if ((jsonObj.get("includeHistoryDetails") != null && !jsonObj.get("includeHistoryDetails").isJsonNull()) && !jsonObj.get("includeHistoryDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `includeHistoryDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("includeHistoryDetails").toString()));
      }
      if ((jsonObj.get("enableTransliterationFlag") != null && !jsonObj.get("enableTransliterationFlag").isJsonNull()) && !jsonObj.get("enableTransliterationFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `enableTransliterationFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("enableTransliterationFlag").toString()));
      }
      if ((jsonObj.get("sendAllFundSrc") != null && !jsonObj.get("sendAllFundSrc").isJsonNull()) && !jsonObj.get("sendAllFundSrc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendAllFundSrc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendAllFundSrc").toString()));
      }
      if ((jsonObj.get("sendAllPhoneVvStatus") != null && !jsonObj.get("sendAllPhoneVvStatus").isJsonNull()) && !jsonObj.get("sendAllPhoneVvStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendAllPhoneVvStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendAllPhoneVvStatus").toString()));
      }
      if ((jsonObj.get("includeReceiverDetails") != null && !jsonObj.get("includeReceiverDetails").isJsonNull()) && !jsonObj.get("includeReceiverDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `includeReceiverDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("includeReceiverDetails").toString()));
      }
      if ((jsonObj.get("sendConsolidatedFundingSources") != null && !jsonObj.get("sendConsolidatedFundingSources").isJsonNull()) && !jsonObj.get("sendConsolidatedFundingSources").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendConsolidatedFundingSources` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendConsolidatedFundingSources").toString()));
      }
      if ((jsonObj.get("sendConsolidatedReceivers") != null && !jsonObj.get("sendConsolidatedReceivers").isJsonNull()) && !jsonObj.get("sendConsolidatedReceivers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendConsolidatedReceivers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendConsolidatedReceivers").toString()));
      }
      if (!jsonObj.get("requestInitiatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestInitiatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestInitiatedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerLookupByGalacticIdRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerLookupByGalacticIdRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerLookupByGalacticIdRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerLookupByGalacticIdRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerLookupByGalacticIdRequest>() {
           @Override
           public void write(JsonWriter out, CustomerLookupByGalacticIdRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerLookupByGalacticIdRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CustomerLookupByGalacticIdRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CustomerLookupByGalacticIdRequest
  * @throws IOException if the JSON string is invalid with respect to CustomerLookupByGalacticIdRequest
  */
  public static CustomerLookupByGalacticIdRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerLookupByGalacticIdRequest.class);
  }

 /**
  * Convert an instance of CustomerLookupByGalacticIdRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

