/*
 * ucd_clkup_v1_api
 * Swagger documentation for UCD Customer Lookup Service API
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.customerlookup;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Set;

/**
 * This is the request model for LookupCustomerLevelReceiver service. This is to search for a receiver  among a customer’s receivers using customer and receiver key elements and return the receiver details
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T20:02:06.369160100+05:30[Asia/Calcutta]")
public class LookupCustomerLevelReceiverRequest {
  public static final String SERIALIZED_NAME_HEADER = "header";
  @SerializedName(SERIALIZED_NAME_HEADER)
  private Header header;

  public static final String SERIALIZED_NAME_CUSTOMER_UMN = "customerUmn";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_UMN)
  private String customerUmn;

  /**
   * This field indicates to return MyWu Customers or Non-MyWU Customers or both. This flag will be defaulted to N. * If the flag value is Y, then the search will be for MyWU + Non-MyWU customers. * If the flag value is N, then the search will be for MyWU customers only. 
   */
  @JsonAdapter(SendNonWuAlsoFlagEnum.Adapter.class)
  public enum SendNonWuAlsoFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendNonWuAlsoFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendNonWuAlsoFlagEnum fromValue(String value) {
      for (SendNonWuAlsoFlagEnum b : SendNonWuAlsoFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendNonWuAlsoFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendNonWuAlsoFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendNonWuAlsoFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendNonWuAlsoFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_NON_WU_ALSO_FLAG = "sendNonWuAlsoFlag";
  @SerializedName(SERIALIZED_NAME_SEND_NON_WU_ALSO_FLAG)
  private SendNonWuAlsoFlagEnum sendNonWuAlsoFlag = SendNonWuAlsoFlagEnum.Y;

  public static final String SERIALIZED_NAME_RECEIVER_SEQ = "receiverSeq";
  @SerializedName(SERIALIZED_NAME_RECEIVER_SEQ)
  private String receiverSeq;

  public static final String SERIALIZED_NAME_RECEIVER_NO = "receiverNo";
  @SerializedName(SERIALIZED_NAME_RECEIVER_NO)
  private Integer receiverNo;

  /**
   * This flag indicates that the response should include Partial Customers or not. This flag will be defaulted to N. * If the flag value is Y, then the search will be for Full + Partial customers. * If the flag value is N, then the search will be for Full customers only. 
   */
  @JsonAdapter(SendPartialCustomerFlagEnum.Adapter.class)
  public enum SendPartialCustomerFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendPartialCustomerFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendPartialCustomerFlagEnum fromValue(String value) {
      for (SendPartialCustomerFlagEnum b : SendPartialCustomerFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendPartialCustomerFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendPartialCustomerFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendPartialCustomerFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendPartialCustomerFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_PARTIAL_CUSTOMER_FLAG = "sendPartialCustomerFlag";
  @SerializedName(SERIALIZED_NAME_SEND_PARTIAL_CUSTOMER_FLAG)
  private SendPartialCustomerFlagEnum sendPartialCustomerFlag = SendPartialCustomerFlagEnum.N;

  /**
   * This flag indicates that the search should include Convenience Customers or not. This flag will be defaulted to N. * If the flag value is Y, then the search will happen across Convenience, Digital(Full) &amp; Retail(MyWU) Customers.  * If the flag value is N, then the search will happen across Digital(Full) &amp; Retail(MyWU) Customers. 
   */
  @JsonAdapter(IncludeConvenienceFlagEnum.Adapter.class)
  public enum IncludeConvenienceFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    IncludeConvenienceFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IncludeConvenienceFlagEnum fromValue(String value) {
      for (IncludeConvenienceFlagEnum b : IncludeConvenienceFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IncludeConvenienceFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IncludeConvenienceFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IncludeConvenienceFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IncludeConvenienceFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_INCLUDE_CONVENIENCE_FLAG = "includeConvenienceFlag";
  @SerializedName(SERIALIZED_NAME_INCLUDE_CONVENIENCE_FLAG)
  private IncludeConvenienceFlagEnum includeConvenienceFlag = IncludeConvenienceFlagEnum.N;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  private String platform = "W";

  /**
   * This flag would indicate to include Customers with level codes - XXC, WU6 &amp; WU7 or not.   * If this flag is N or not sent, then by the search will not return customer(s) with level code - XXC, WU6 &amp; WU7.    * If this flag value is Y, then the search will return customer(s) irrespective of the level codes. 
   */
  @JsonAdapter(SendAllPfcEnum.Adapter.class)
  public enum SendAllPfcEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendAllPfcEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendAllPfcEnum fromValue(String value) {
      for (SendAllPfcEnum b : SendAllPfcEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendAllPfcEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendAllPfcEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendAllPfcEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendAllPfcEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_ALL_PFC = "sendAllPfc";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_PFC)
  private SendAllPfcEnum sendAllPfc = SendAllPfcEnum.N;

  /**
   * This flag indicates to/not to convert the Special Characters to ASCII for Sender &amp; Receiver details (Name, Address, Address in UAB). For Loyalty, this flag will be defaulted to Y and for others this falg will be defaulted to N. * If passed as N in the request, as is values will be returned in response. * If passed as Y in the request, the Special Characters will be converted to ASCII and will be returned in response. 
   */
  @JsonAdapter(EnableTransliterationFlagEnum.Adapter.class)
  public enum EnableTransliterationFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    EnableTransliterationFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EnableTransliterationFlagEnum fromValue(String value) {
      for (EnableTransliterationFlagEnum b : EnableTransliterationFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EnableTransliterationFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EnableTransliterationFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EnableTransliterationFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EnableTransliterationFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ENABLE_TRANSLITERATION_FLAG = "enableTransliterationFlag";
  @SerializedName(SERIALIZED_NAME_ENABLE_TRANSLITERATION_FLAG)
  private EnableTransliterationFlagEnum enableTransliterationFlag = EnableTransliterationFlagEnum.N;

  /**
   * This flag indicates that the response should include All Funding Sources or not. This flag will be defaulted to N. * If the flag value is &#39;Y&#39;, then the search will happen for all funding sources including the funding sources added by TMT. * If the flag value is &#39;N&#39;, then the search will happen for all funding sources excluding the funding sources added by TMT. 
   */
  @JsonAdapter(SendAllFundSrcEnum.Adapter.class)
  public enum SendAllFundSrcEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendAllFundSrcEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendAllFundSrcEnum fromValue(String value) {
      for (SendAllFundSrcEnum b : SendAllFundSrcEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendAllFundSrcEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendAllFundSrcEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendAllFundSrcEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendAllFundSrcEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_ALL_FUND_SRC = "sendAllFundSrc";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_FUND_SRC)
  private SendAllFundSrcEnum sendAllFundSrc = SendAllFundSrcEnum.N;

  /**
   * This flag indicates that the response should include All Phone Verification Statases or not. This flag will be defaulted to N. * If the flag value is &#39;Y&#39;, then the phoneVvStatus - Z / T / R / S / V / A / B / U / C / D will be returned if available. * If the flag value is &#39;N&#39;, then only the phoneVvStatus - N / L / M / P will be returned if available. 
   */
  @JsonAdapter(SendAllPhoneVvStatusEnum.Adapter.class)
  public enum SendAllPhoneVvStatusEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendAllPhoneVvStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendAllPhoneVvStatusEnum fromValue(String value) {
      for (SendAllPhoneVvStatusEnum b : SendAllPhoneVvStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendAllPhoneVvStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendAllPhoneVvStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendAllPhoneVvStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendAllPhoneVvStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_ALL_PHONE_VV_STATUS = "sendAllPhoneVvStatus";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_PHONE_VV_STATUS)
  private SendAllPhoneVvStatusEnum sendAllPhoneVvStatus = SendAllPhoneVvStatusEnum.N;

  /**
   * Flag which indicates to search across All profiles or only Primary UMN profile. * If not passed in the request, all the profiles will be returned in response by default. * If passed as N in the request, all the profiles will be returned in response. * If passed as Y in the request, then   * Only the Primary UMN profile will be returned in response.   * platform will get defaulted to A   * noOfYearsInSearch passed in the request will get ignored 
   */
  @JsonAdapter(EnableCrossChannelFlagEnum.Adapter.class)
  public enum EnableCrossChannelFlagEnum {
    Y("Y"),
    
    N("N");

    private String value;

    EnableCrossChannelFlagEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EnableCrossChannelFlagEnum fromValue(String value) {
      for (EnableCrossChannelFlagEnum b : EnableCrossChannelFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EnableCrossChannelFlagEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EnableCrossChannelFlagEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EnableCrossChannelFlagEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EnableCrossChannelFlagEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ENABLE_CROSS_CHANNEL_FLAG = "enableCrossChannelFlag";
  @SerializedName(SERIALIZED_NAME_ENABLE_CROSS_CHANNEL_FLAG)
  private EnableCrossChannelFlagEnum enableCrossChannelFlag = EnableCrossChannelFlagEnum.N;

  /**
   * This flag would indicate to include consolidated funding sources from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return funding sources from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated funding sources from both primary &amp; scondary profiles. 
   */
  @JsonAdapter(SendConsolidatedFundingSourcesEnum.Adapter.class)
  public enum SendConsolidatedFundingSourcesEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendConsolidatedFundingSourcesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendConsolidatedFundingSourcesEnum fromValue(String value) {
      for (SendConsolidatedFundingSourcesEnum b : SendConsolidatedFundingSourcesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendConsolidatedFundingSourcesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendConsolidatedFundingSourcesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendConsolidatedFundingSourcesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendConsolidatedFundingSourcesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_CONSOLIDATED_FUNDING_SOURCES = "sendConsolidatedFundingSources";
  @SerializedName(SERIALIZED_NAME_SEND_CONSOLIDATED_FUNDING_SOURCES)
  private SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources = SendConsolidatedFundingSourcesEnum.N;

  /**
   * This flag would indicate to include consolidated receviers from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return receviers from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated receivers from both primary &amp; scondary profiles. 
   */
  @JsonAdapter(SendConsolidatedReceiversEnum.Adapter.class)
  public enum SendConsolidatedReceiversEnum {
    Y("Y"),
    
    N("N");

    private String value;

    SendConsolidatedReceiversEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SendConsolidatedReceiversEnum fromValue(String value) {
      for (SendConsolidatedReceiversEnum b : SendConsolidatedReceiversEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SendConsolidatedReceiversEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SendConsolidatedReceiversEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SendConsolidatedReceiversEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SendConsolidatedReceiversEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SEND_CONSOLIDATED_RECEIVERS = "sendConsolidatedReceivers";
  @SerializedName(SERIALIZED_NAME_SEND_CONSOLIDATED_RECEIVERS)
  private SendConsolidatedReceiversEnum sendConsolidatedReceivers = SendConsolidatedReceiversEnum.N;

  public static final String SERIALIZED_NAME_COUNTRY_CODE_ISO2 = "countryCodeIso2";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE_ISO2)
  private String countryCodeIso2;

  public static final String SERIALIZED_NAME_COUNTRY_CODE_ISO3 = "countryCodeIso3";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE_ISO3)
  private String countryCodeIso3;

  public static final String SERIALIZED_NAME_REQUEST_INITIATED_BY = "requestInitiatedBy";
  @SerializedName(SERIALIZED_NAME_REQUEST_INITIATED_BY)
  private String requestInitiatedBy;

  public LookupCustomerLevelReceiverRequest() {
  }

  public LookupCustomerLevelReceiverRequest header(Header header) {
    
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @javax.annotation.Nonnull
  public Header getHeader() {
    return header;
  }


  public void setHeader(Header header) {
    this.header = header;
  }


  public LookupCustomerLevelReceiverRequest customerUmn(String customerUmn) {
    
    this.customerUmn = customerUmn;
    return this;
  }

   /**
   * Customer UMN
   * @return customerUmn
  **/
  @javax.annotation.Nonnull
  public String getCustomerUmn() {
    return customerUmn;
  }


  public void setCustomerUmn(String customerUmn) {
    this.customerUmn = customerUmn;
  }


  public LookupCustomerLevelReceiverRequest sendNonWuAlsoFlag(SendNonWuAlsoFlagEnum sendNonWuAlsoFlag) {
    
    this.sendNonWuAlsoFlag = sendNonWuAlsoFlag;
    return this;
  }

   /**
   * This field indicates to return MyWu Customers or Non-MyWU Customers or both. This flag will be defaulted to N. * If the flag value is Y, then the search will be for MyWU + Non-MyWU customers. * If the flag value is N, then the search will be for MyWU customers only. 
   * @return sendNonWuAlsoFlag
  **/
  @javax.annotation.Nullable
  public SendNonWuAlsoFlagEnum getSendNonWuAlsoFlag() {
    return sendNonWuAlsoFlag;
  }


  public void setSendNonWuAlsoFlag(SendNonWuAlsoFlagEnum sendNonWuAlsoFlag) {
    this.sendNonWuAlsoFlag = sendNonWuAlsoFlag;
  }


  public LookupCustomerLevelReceiverRequest receiverSeq(String receiverSeq) {
    
    this.receiverSeq = receiverSeq;
    return this;
  }

   /**
   * This field indicates to return the customer&#39;s details and the receiver details for the given receiverSeq.
   * @return receiverSeq
  **/
  @javax.annotation.Nullable
  public String getReceiverSeq() {
    return receiverSeq;
  }


  public void setReceiverSeq(String receiverSeq) {
    this.receiverSeq = receiverSeq;
  }


  public LookupCustomerLevelReceiverRequest receiverNo(Integer receiverNo) {
    
    this.receiverNo = receiverNo;
    return this;
  }

   /**
   * This field indicates to return the customer&#39;s details and the receiver details for the given receiverNo.
   * @return receiverNo
  **/
  @javax.annotation.Nonnull
  public Integer getReceiverNo() {
    return receiverNo;
  }


  public void setReceiverNo(Integer receiverNo) {
    this.receiverNo = receiverNo;
  }


  public LookupCustomerLevelReceiverRequest sendPartialCustomerFlag(SendPartialCustomerFlagEnum sendPartialCustomerFlag) {
    
    this.sendPartialCustomerFlag = sendPartialCustomerFlag;
    return this;
  }

   /**
   * This flag indicates that the response should include Partial Customers or not. This flag will be defaulted to N. * If the flag value is Y, then the search will be for Full + Partial customers. * If the flag value is N, then the search will be for Full customers only. 
   * @return sendPartialCustomerFlag
  **/
  @javax.annotation.Nullable
  public SendPartialCustomerFlagEnum getSendPartialCustomerFlag() {
    return sendPartialCustomerFlag;
  }


  public void setSendPartialCustomerFlag(SendPartialCustomerFlagEnum sendPartialCustomerFlag) {
    this.sendPartialCustomerFlag = sendPartialCustomerFlag;
  }


  public LookupCustomerLevelReceiverRequest includeConvenienceFlag(IncludeConvenienceFlagEnum includeConvenienceFlag) {
    
    this.includeConvenienceFlag = includeConvenienceFlag;
    return this;
  }

   /**
   * This flag indicates that the search should include Convenience Customers or not. This flag will be defaulted to N. * If the flag value is Y, then the search will happen across Convenience, Digital(Full) &amp; Retail(MyWU) Customers.  * If the flag value is N, then the search will happen across Digital(Full) &amp; Retail(MyWU) Customers. 
   * @return includeConvenienceFlag
  **/
  @javax.annotation.Nullable
  public IncludeConvenienceFlagEnum getIncludeConvenienceFlag() {
    return includeConvenienceFlag;
  }


  public void setIncludeConvenienceFlag(IncludeConvenienceFlagEnum includeConvenienceFlag) {
    this.includeConvenienceFlag = includeConvenienceFlag;
  }


  public LookupCustomerLevelReceiverRequest platform(String platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * This flag indicates that the search should happen across all/specific paltform(s). For Phoenix, this flag will be defaulted to A and for Non-Phoenix, this flag will be defaulted to W. * If the flag value is \&quot;A\&quot;, then the search will happen irrespective of platform. * If the flag value is \&quot;O\&quot;, then the search will happen in only OVI platform. * If the flag value is \&quot;V\&quot;, then the search will happen in only VIGO platform. * if the flag value is \&quot;W\&quot;, then the search will happen other than OVI/VIGO platforms. 
   * @return platform
  **/
  @javax.annotation.Nullable
  public String getPlatform() {
    return platform;
  }


  public void setPlatform(String platform) {
    this.platform = platform;
  }


  public LookupCustomerLevelReceiverRequest sendAllPfc(SendAllPfcEnum sendAllPfc) {
    
    this.sendAllPfc = sendAllPfc;
    return this;
  }

   /**
   * This flag would indicate to include Customers with level codes - XXC, WU6 &amp; WU7 or not.   * If this flag is N or not sent, then by the search will not return customer(s) with level code - XXC, WU6 &amp; WU7.    * If this flag value is Y, then the search will return customer(s) irrespective of the level codes. 
   * @return sendAllPfc
  **/
  @javax.annotation.Nullable
  public SendAllPfcEnum getSendAllPfc() {
    return sendAllPfc;
  }


  public void setSendAllPfc(SendAllPfcEnum sendAllPfc) {
    this.sendAllPfc = sendAllPfc;
  }


  public LookupCustomerLevelReceiverRequest enableTransliterationFlag(EnableTransliterationFlagEnum enableTransliterationFlag) {
    
    this.enableTransliterationFlag = enableTransliterationFlag;
    return this;
  }

   /**
   * This flag indicates to/not to convert the Special Characters to ASCII for Sender &amp; Receiver details (Name, Address, Address in UAB). For Loyalty, this flag will be defaulted to Y and for others this falg will be defaulted to N. * If passed as N in the request, as is values will be returned in response. * If passed as Y in the request, the Special Characters will be converted to ASCII and will be returned in response. 
   * @return enableTransliterationFlag
  **/
  @javax.annotation.Nullable
  public EnableTransliterationFlagEnum getEnableTransliterationFlag() {
    return enableTransliterationFlag;
  }


  public void setEnableTransliterationFlag(EnableTransliterationFlagEnum enableTransliterationFlag) {
    this.enableTransliterationFlag = enableTransliterationFlag;
  }


  public LookupCustomerLevelReceiverRequest sendAllFundSrc(SendAllFundSrcEnum sendAllFundSrc) {
    
    this.sendAllFundSrc = sendAllFundSrc;
    return this;
  }

   /**
   * This flag indicates that the response should include All Funding Sources or not. This flag will be defaulted to N. * If the flag value is &#39;Y&#39;, then the search will happen for all funding sources including the funding sources added by TMT. * If the flag value is &#39;N&#39;, then the search will happen for all funding sources excluding the funding sources added by TMT. 
   * @return sendAllFundSrc
  **/
  @javax.annotation.Nullable
  public SendAllFundSrcEnum getSendAllFundSrc() {
    return sendAllFundSrc;
  }


  public void setSendAllFundSrc(SendAllFundSrcEnum sendAllFundSrc) {
    this.sendAllFundSrc = sendAllFundSrc;
  }


  public LookupCustomerLevelReceiverRequest sendAllPhoneVvStatus(SendAllPhoneVvStatusEnum sendAllPhoneVvStatus) {
    
    this.sendAllPhoneVvStatus = sendAllPhoneVvStatus;
    return this;
  }

   /**
   * This flag indicates that the response should include All Phone Verification Statases or not. This flag will be defaulted to N. * If the flag value is &#39;Y&#39;, then the phoneVvStatus - Z / T / R / S / V / A / B / U / C / D will be returned if available. * If the flag value is &#39;N&#39;, then only the phoneVvStatus - N / L / M / P will be returned if available. 
   * @return sendAllPhoneVvStatus
  **/
  @javax.annotation.Nullable
  public SendAllPhoneVvStatusEnum getSendAllPhoneVvStatus() {
    return sendAllPhoneVvStatus;
  }


  public void setSendAllPhoneVvStatus(SendAllPhoneVvStatusEnum sendAllPhoneVvStatus) {
    this.sendAllPhoneVvStatus = sendAllPhoneVvStatus;
  }


  public LookupCustomerLevelReceiverRequest enableCrossChannelFlag(EnableCrossChannelFlagEnum enableCrossChannelFlag) {
    
    this.enableCrossChannelFlag = enableCrossChannelFlag;
    return this;
  }

   /**
   * Flag which indicates to search across All profiles or only Primary UMN profile. * If not passed in the request, all the profiles will be returned in response by default. * If passed as N in the request, all the profiles will be returned in response. * If passed as Y in the request, then   * Only the Primary UMN profile will be returned in response.   * platform will get defaulted to A   * noOfYearsInSearch passed in the request will get ignored 
   * @return enableCrossChannelFlag
  **/
  @javax.annotation.Nullable
  public EnableCrossChannelFlagEnum getEnableCrossChannelFlag() {
    return enableCrossChannelFlag;
  }


  public void setEnableCrossChannelFlag(EnableCrossChannelFlagEnum enableCrossChannelFlag) {
    this.enableCrossChannelFlag = enableCrossChannelFlag;
  }


  public LookupCustomerLevelReceiverRequest sendConsolidatedFundingSources(SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources) {
    
    this.sendConsolidatedFundingSources = sendConsolidatedFundingSources;
    return this;
  }

   /**
   * This flag would indicate to include consolidated funding sources from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return funding sources from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated funding sources from both primary &amp; scondary profiles. 
   * @return sendConsolidatedFundingSources
  **/
  @javax.annotation.Nullable
  public SendConsolidatedFundingSourcesEnum getSendConsolidatedFundingSources() {
    return sendConsolidatedFundingSources;
  }


  public void setSendConsolidatedFundingSources(SendConsolidatedFundingSourcesEnum sendConsolidatedFundingSources) {
    this.sendConsolidatedFundingSources = sendConsolidatedFundingSources;
  }


  public LookupCustomerLevelReceiverRequest sendConsolidatedReceivers(SendConsolidatedReceiversEnum sendConsolidatedReceivers) {
    
    this.sendConsolidatedReceivers = sendConsolidatedReceivers;
    return this;
  }

   /**
   * This flag would indicate to include consolidated receviers from both primary &amp; secondary profiles or not.   * If this flag value is &#39;N&#39; or not sent, then it will return receviers from primary profile only.   * If the flag value is &#39;Y&#39;, then web service will return consolidated receivers from both primary &amp; scondary profiles. 
   * @return sendConsolidatedReceivers
  **/
  @javax.annotation.Nullable
  public SendConsolidatedReceiversEnum getSendConsolidatedReceivers() {
    return sendConsolidatedReceivers;
  }


  public void setSendConsolidatedReceivers(SendConsolidatedReceiversEnum sendConsolidatedReceivers) {
    this.sendConsolidatedReceivers = sendConsolidatedReceivers;
  }


  public LookupCustomerLevelReceiverRequest countryCodeIso2(String countryCodeIso2) {
    
    this.countryCodeIso2 = countryCodeIso2;
    return this;
  }

   /**
   * Country code in ISO2 format. e.g. AT, IN, US etc. If countryCodeIso1 is passed and if the country is SCV enbaled, then   * enableCrossChannelFlag will get defaulted to Y   * platform will get defaulted to A\\   * noOfYearsInSearch passed in the request will get ignored 
   * @return countryCodeIso2
  **/
  @javax.annotation.Nullable
  public String getCountryCodeIso2() {
    return countryCodeIso2;
  }


  public void setCountryCodeIso2(String countryCodeIso2) {
    this.countryCodeIso2 = countryCodeIso2;
  }


  public LookupCustomerLevelReceiverRequest countryCodeIso3(String countryCodeIso3) {
    
    this.countryCodeIso3 = countryCodeIso3;
    return this;
  }

   /**
   * Country code in ISO3 format. e.g. AUT, IND, USA etc. If countryCodeIso1 is passed and if the country is SCV enbaled, then   * enableCrossChannelFlag will get defaulted to Y   * platform will get defaulted to A\\   * noOfYearsInSearch passed in the request will get ignored 
   * @return countryCodeIso3
  **/
  @javax.annotation.Nullable
  public String getCountryCodeIso3() {
    return countryCodeIso3;
  }


  public void setCountryCodeIso3(String countryCodeIso3) {
    this.countryCodeIso3 = countryCodeIso3;
  }


  public LookupCustomerLevelReceiverRequest requestInitiatedBy(String requestInitiatedBy) {
    
    this.requestInitiatedBy = requestInitiatedBy;
    return this;
  }

   /**
   * To identify who has initiated the request.
   * @return requestInitiatedBy
  **/
  @javax.annotation.Nullable
  public String getRequestInitiatedBy() {
    return requestInitiatedBy;
  }


  public void setRequestInitiatedBy(String requestInitiatedBy) {
    this.requestInitiatedBy = requestInitiatedBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LookupCustomerLevelReceiverRequest lookupCustomerLevelReceiverRequest = (LookupCustomerLevelReceiverRequest) o;
    return Objects.equals(this.header, lookupCustomerLevelReceiverRequest.header) &&
        Objects.equals(this.customerUmn, lookupCustomerLevelReceiverRequest.customerUmn) &&
        Objects.equals(this.sendNonWuAlsoFlag, lookupCustomerLevelReceiverRequest.sendNonWuAlsoFlag) &&
        Objects.equals(this.receiverSeq, lookupCustomerLevelReceiverRequest.receiverSeq) &&
        Objects.equals(this.receiverNo, lookupCustomerLevelReceiverRequest.receiverNo) &&
        Objects.equals(this.sendPartialCustomerFlag, lookupCustomerLevelReceiverRequest.sendPartialCustomerFlag) &&
        Objects.equals(this.includeConvenienceFlag, lookupCustomerLevelReceiverRequest.includeConvenienceFlag) &&
        Objects.equals(this.platform, lookupCustomerLevelReceiverRequest.platform) &&
        Objects.equals(this.sendAllPfc, lookupCustomerLevelReceiverRequest.sendAllPfc) &&
        Objects.equals(this.enableTransliterationFlag, lookupCustomerLevelReceiverRequest.enableTransliterationFlag) &&
        Objects.equals(this.sendAllFundSrc, lookupCustomerLevelReceiverRequest.sendAllFundSrc) &&
        Objects.equals(this.sendAllPhoneVvStatus, lookupCustomerLevelReceiverRequest.sendAllPhoneVvStatus) &&
        Objects.equals(this.enableCrossChannelFlag, lookupCustomerLevelReceiverRequest.enableCrossChannelFlag) &&
        Objects.equals(this.sendConsolidatedFundingSources, lookupCustomerLevelReceiverRequest.sendConsolidatedFundingSources) &&
        Objects.equals(this.sendConsolidatedReceivers, lookupCustomerLevelReceiverRequest.sendConsolidatedReceivers) &&
        Objects.equals(this.countryCodeIso2, lookupCustomerLevelReceiverRequest.countryCodeIso2) &&
        Objects.equals(this.countryCodeIso3, lookupCustomerLevelReceiverRequest.countryCodeIso3) &&
        Objects.equals(this.requestInitiatedBy, lookupCustomerLevelReceiverRequest.requestInitiatedBy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, customerUmn, sendNonWuAlsoFlag, receiverSeq, receiverNo, sendPartialCustomerFlag, includeConvenienceFlag, platform, sendAllPfc, enableTransliterationFlag, sendAllFundSrc, sendAllPhoneVvStatus, enableCrossChannelFlag, sendConsolidatedFundingSources, sendConsolidatedReceivers, countryCodeIso2, countryCodeIso3, requestInitiatedBy);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LookupCustomerLevelReceiverRequest {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    customerUmn: ").append(toIndentedString(customerUmn)).append("\n");
    sb.append("    sendNonWuAlsoFlag: ").append(toIndentedString(sendNonWuAlsoFlag)).append("\n");
    sb.append("    receiverSeq: ").append(toIndentedString(receiverSeq)).append("\n");
    sb.append("    receiverNo: ").append(toIndentedString(receiverNo)).append("\n");
    sb.append("    sendPartialCustomerFlag: ").append(toIndentedString(sendPartialCustomerFlag)).append("\n");
    sb.append("    includeConvenienceFlag: ").append(toIndentedString(includeConvenienceFlag)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    sendAllPfc: ").append(toIndentedString(sendAllPfc)).append("\n");
    sb.append("    enableTransliterationFlag: ").append(toIndentedString(enableTransliterationFlag)).append("\n");
    sb.append("    sendAllFundSrc: ").append(toIndentedString(sendAllFundSrc)).append("\n");
    sb.append("    sendAllPhoneVvStatus: ").append(toIndentedString(sendAllPhoneVvStatus)).append("\n");
    sb.append("    enableCrossChannelFlag: ").append(toIndentedString(enableCrossChannelFlag)).append("\n");
    sb.append("    sendConsolidatedFundingSources: ").append(toIndentedString(sendConsolidatedFundingSources)).append("\n");
    sb.append("    sendConsolidatedReceivers: ").append(toIndentedString(sendConsolidatedReceivers)).append("\n");
    sb.append("    countryCodeIso2: ").append(toIndentedString(countryCodeIso2)).append("\n");
    sb.append("    countryCodeIso3: ").append(toIndentedString(countryCodeIso3)).append("\n");
    sb.append("    requestInitiatedBy: ").append(toIndentedString(requestInitiatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("header");
    openapiFields.add("customerUmn");
    openapiFields.add("sendNonWuAlsoFlag");
    openapiFields.add("receiverSeq");
    openapiFields.add("receiverNo");
    openapiFields.add("sendPartialCustomerFlag");
    openapiFields.add("includeConvenienceFlag");
    openapiFields.add("platform");
    openapiFields.add("sendAllPfc");
    openapiFields.add("enableTransliterationFlag");
    openapiFields.add("sendAllFundSrc");
    openapiFields.add("sendAllPhoneVvStatus");
    openapiFields.add("enableCrossChannelFlag");
    openapiFields.add("sendConsolidatedFundingSources");
    openapiFields.add("sendConsolidatedReceivers");
    openapiFields.add("countryCodeIso2");
    openapiFields.add("countryCodeIso3");
    openapiFields.add("requestInitiatedBy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("header");
    openapiRequiredFields.add("customerUmn");
    openapiRequiredFields.add("receiverNo");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LookupCustomerLevelReceiverRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LookupCustomerLevelReceiverRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LookupCustomerLevelReceiverRequest is not found in the empty JSON string", LookupCustomerLevelReceiverRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LookupCustomerLevelReceiverRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LookupCustomerLevelReceiverRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LookupCustomerLevelReceiverRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `header`
      Header.validateJsonObject(jsonObj.getAsJsonObject("header"));
      if (!jsonObj.get("customerUmn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerUmn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerUmn").toString()));
      }
      if ((jsonObj.get("sendNonWuAlsoFlag") != null && !jsonObj.get("sendNonWuAlsoFlag").isJsonNull()) && !jsonObj.get("sendNonWuAlsoFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendNonWuAlsoFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendNonWuAlsoFlag").toString()));
      }
      if ((jsonObj.get("receiverSeq") != null && !jsonObj.get("receiverSeq").isJsonNull()) && !jsonObj.get("receiverSeq").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiverSeq` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiverSeq").toString()));
      }
      if ((jsonObj.get("sendPartialCustomerFlag") != null && !jsonObj.get("sendPartialCustomerFlag").isJsonNull()) && !jsonObj.get("sendPartialCustomerFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendPartialCustomerFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendPartialCustomerFlag").toString()));
      }
      if ((jsonObj.get("includeConvenienceFlag") != null && !jsonObj.get("includeConvenienceFlag").isJsonNull()) && !jsonObj.get("includeConvenienceFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `includeConvenienceFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("includeConvenienceFlag").toString()));
      }
      if ((jsonObj.get("platform") != null && !jsonObj.get("platform").isJsonNull()) && !jsonObj.get("platform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `platform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform").toString()));
      }
      if ((jsonObj.get("sendAllPfc") != null && !jsonObj.get("sendAllPfc").isJsonNull()) && !jsonObj.get("sendAllPfc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendAllPfc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendAllPfc").toString()));
      }
      if ((jsonObj.get("enableTransliterationFlag") != null && !jsonObj.get("enableTransliterationFlag").isJsonNull()) && !jsonObj.get("enableTransliterationFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `enableTransliterationFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("enableTransliterationFlag").toString()));
      }
      if ((jsonObj.get("sendAllFundSrc") != null && !jsonObj.get("sendAllFundSrc").isJsonNull()) && !jsonObj.get("sendAllFundSrc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendAllFundSrc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendAllFundSrc").toString()));
      }
      if ((jsonObj.get("sendAllPhoneVvStatus") != null && !jsonObj.get("sendAllPhoneVvStatus").isJsonNull()) && !jsonObj.get("sendAllPhoneVvStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendAllPhoneVvStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendAllPhoneVvStatus").toString()));
      }
      if ((jsonObj.get("enableCrossChannelFlag") != null && !jsonObj.get("enableCrossChannelFlag").isJsonNull()) && !jsonObj.get("enableCrossChannelFlag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `enableCrossChannelFlag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("enableCrossChannelFlag").toString()));
      }
      if ((jsonObj.get("sendConsolidatedFundingSources") != null && !jsonObj.get("sendConsolidatedFundingSources").isJsonNull()) && !jsonObj.get("sendConsolidatedFundingSources").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendConsolidatedFundingSources` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendConsolidatedFundingSources").toString()));
      }
      if ((jsonObj.get("sendConsolidatedReceivers") != null && !jsonObj.get("sendConsolidatedReceivers").isJsonNull()) && !jsonObj.get("sendConsolidatedReceivers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sendConsolidatedReceivers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendConsolidatedReceivers").toString()));
      }
      if ((jsonObj.get("countryCodeIso2") != null && !jsonObj.get("countryCodeIso2").isJsonNull()) && !jsonObj.get("countryCodeIso2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCodeIso2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCodeIso2").toString()));
      }
      if ((jsonObj.get("countryCodeIso3") != null && !jsonObj.get("countryCodeIso3").isJsonNull()) && !jsonObj.get("countryCodeIso3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCodeIso3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCodeIso3").toString()));
      }
      if ((jsonObj.get("requestInitiatedBy") != null && !jsonObj.get("requestInitiatedBy").isJsonNull()) && !jsonObj.get("requestInitiatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestInitiatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestInitiatedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LookupCustomerLevelReceiverRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LookupCustomerLevelReceiverRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LookupCustomerLevelReceiverRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LookupCustomerLevelReceiverRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<LookupCustomerLevelReceiverRequest>() {
           @Override
           public void write(JsonWriter out, LookupCustomerLevelReceiverRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LookupCustomerLevelReceiverRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LookupCustomerLevelReceiverRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LookupCustomerLevelReceiverRequest
  * @throws IOException if the JSON string is invalid with respect to LookupCustomerLevelReceiverRequest
  */
  public static LookupCustomerLevelReceiverRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LookupCustomerLevelReceiverRequest.class);
  }

 /**
  * Convert an instance of LookupCustomerLevelReceiverRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

