/*
 * ucd_clkup_v1_api
 * Swagger documentation for UCD Customer Lookup Service API
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.customerlookup;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/**
 * PepProfileEntities
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T20:02:06.369160100+05:30[Asia/Calcutta]")
public class PepProfileEntities {
  public static final String SERIALIZED_NAME_GALACTIC_ID = "galacticId";
  @SerializedName(SERIALIZED_NAME_GALACTIC_ID)
  private String galacticId;

  public static final String SERIALIZED_NAME_ENTITY_ID = "entityId";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  private Integer entityId;

  public static final String SERIALIZED_NAME_UNIV_SPECIFIC_ID = "univSpecificId";
  @SerializedName(SERIALIZED_NAME_UNIV_SPECIFIC_ID)
  private String univSpecificId;

  public static final String SERIALIZED_NAME_IS_TRUE_MATCH = "isTrueMatch";
  @SerializedName(SERIALIZED_NAME_IS_TRUE_MATCH)
  private String isTrueMatch;

  public static final String SERIALIZED_NAME_EFFECTIVE_DATE = "effectiveDate";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_DATE)
  private String effectiveDate;

  public static final String SERIALIZED_NAME_IS_CASE_CLOSED = "isCaseClosed";
  @SerializedName(SERIALIZED_NAME_IS_CASE_CLOSED)
  private String isCaseClosed;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private String createdDate;

  public static final String SERIALIZED_NAME_UPDATED_BY = "updatedBy";
  @SerializedName(SERIALIZED_NAME_UPDATED_BY)
  private String updatedBy;

  public static final String SERIALIZED_NAME_UPDATED_DATE = "updatedDate";
  @SerializedName(SERIALIZED_NAME_UPDATED_DATE)
  private String updatedDate;

  public static final String SERIALIZED_NAME_DELETED_BY = "deletedBy";
  @SerializedName(SERIALIZED_NAME_DELETED_BY)
  private String deletedBy;

  public static final String SERIALIZED_NAME_DELETED_DATE = "deletedDate";
  @SerializedName(SERIALIZED_NAME_DELETED_DATE)
  private String deletedDate;

  public PepProfileEntities() {
  }

  public PepProfileEntities galacticId(String galacticId) {
    
    this.galacticId = galacticId;
    return this;
  }

   /**
   * Galactic ID generated by EAS system. It is used by Compliance system to find unique customer.
   * @return galacticId
  **/
  @javax.annotation.Nonnull
  public String getGalacticId() {
    return galacticId;
  }


  public void setGalacticId(String galacticId) {
    this.galacticId = galacticId;
  }


  public PepProfileEntities entityId(Integer entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Entity ID.
   * @return entityId
  **/
  @javax.annotation.Nonnull
  public Integer getEntityId() {
    return entityId;
  }


  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }


  public PepProfileEntities univSpecificId(String univSpecificId) {
    
    this.univSpecificId = univSpecificId;
    return this;
  }

   /**
   * Universal Specific ID.
   * @return univSpecificId
  **/
  @javax.annotation.Nonnull
  public String getUnivSpecificId() {
    return univSpecificId;
  }


  public void setUnivSpecificId(String univSpecificId) {
    this.univSpecificId = univSpecificId;
  }


  public PepProfileEntities isTrueMatch(String isTrueMatch) {
    
    this.isTrueMatch = isTrueMatch;
    return this;
  }

   /**
   * This flag indicates whether the match is true or not.
   * @return isTrueMatch
  **/
  @javax.annotation.Nullable
  public String getIsTrueMatch() {
    return isTrueMatch;
  }


  public void setIsTrueMatch(String isTrueMatch) {
    this.isTrueMatch = isTrueMatch;
  }


  public PepProfileEntities effectiveDate(String effectiveDate) {
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Effective Timestamp.
   * @return effectiveDate
  **/
  @javax.annotation.Nullable
  public String getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }


  public PepProfileEntities isCaseClosed(String isCaseClosed) {
    
    this.isCaseClosed = isCaseClosed;
    return this;
  }

   /**
   * This flag indicates whether the case is closed or not.
   * @return isCaseClosed
  **/
  @javax.annotation.Nullable
  public String getIsCaseClosed() {
    return isCaseClosed;
  }


  public void setIsCaseClosed(String isCaseClosed) {
    this.isCaseClosed = isCaseClosed;
  }


  public PepProfileEntities comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Comments.
   * @return comments
  **/
  @javax.annotation.Nullable
  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public PepProfileEntities createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Application/System/End User who created the record
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public PepProfileEntities createdDate(String createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Timestamp when the Application/System/End User created the record
   * @return createdDate
  **/
  @javax.annotation.Nonnull
  public String getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }


  public PepProfileEntities updatedBy(String updatedBy) {
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Application/System/End User who updated the record
   * @return updatedBy
  **/
  @javax.annotation.Nonnull
  public String getUpdatedBy() {
    return updatedBy;
  }


  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public PepProfileEntities updatedDate(String updatedDate) {
    
    this.updatedDate = updatedDate;
    return this;
  }

   /**
   * Timestamp when the Application/System/End User updated the record
   * @return updatedDate
  **/
  @javax.annotation.Nonnull
  public String getUpdatedDate() {
    return updatedDate;
  }


  public void setUpdatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
  }


  public PepProfileEntities deletedBy(String deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

   /**
   * Application/System/End User who deleted the record
   * @return deletedBy
  **/
  @javax.annotation.Nullable
  public String getDeletedBy() {
    return deletedBy;
  }


  public void setDeletedBy(String deletedBy) {
    this.deletedBy = deletedBy;
  }


  public PepProfileEntities deletedDate(String deletedDate) {
    
    this.deletedDate = deletedDate;
    return this;
  }

   /**
   * Timestamp when the Application/System/End User deleted the record
   * @return deletedDate
  **/
  @javax.annotation.Nullable
  public String getDeletedDate() {
    return deletedDate;
  }


  public void setDeletedDate(String deletedDate) {
    this.deletedDate = deletedDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PepProfileEntities pepProfileEntities = (PepProfileEntities) o;
    return Objects.equals(this.galacticId, pepProfileEntities.galacticId) &&
        Objects.equals(this.entityId, pepProfileEntities.entityId) &&
        Objects.equals(this.univSpecificId, pepProfileEntities.univSpecificId) &&
        Objects.equals(this.isTrueMatch, pepProfileEntities.isTrueMatch) &&
        Objects.equals(this.effectiveDate, pepProfileEntities.effectiveDate) &&
        Objects.equals(this.isCaseClosed, pepProfileEntities.isCaseClosed) &&
        Objects.equals(this.comments, pepProfileEntities.comments) &&
        Objects.equals(this.createdBy, pepProfileEntities.createdBy) &&
        Objects.equals(this.createdDate, pepProfileEntities.createdDate) &&
        Objects.equals(this.updatedBy, pepProfileEntities.updatedBy) &&
        Objects.equals(this.updatedDate, pepProfileEntities.updatedDate) &&
        Objects.equals(this.deletedBy, pepProfileEntities.deletedBy) &&
        Objects.equals(this.deletedDate, pepProfileEntities.deletedDate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(galacticId, entityId, univSpecificId, isTrueMatch, effectiveDate, isCaseClosed, comments, createdBy, createdDate, updatedBy, updatedDate, deletedBy, deletedDate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PepProfileEntities {\n");
    sb.append("    galacticId: ").append(toIndentedString(galacticId)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    univSpecificId: ").append(toIndentedString(univSpecificId)).append("\n");
    sb.append("    isTrueMatch: ").append(toIndentedString(isTrueMatch)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    isCaseClosed: ").append(toIndentedString(isCaseClosed)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    deletedDate: ").append(toIndentedString(deletedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("galacticId");
    openapiFields.add("entityId");
    openapiFields.add("univSpecificId");
    openapiFields.add("isTrueMatch");
    openapiFields.add("effectiveDate");
    openapiFields.add("isCaseClosed");
    openapiFields.add("comments");
    openapiFields.add("createdBy");
    openapiFields.add("createdDate");
    openapiFields.add("updatedBy");
    openapiFields.add("updatedDate");
    openapiFields.add("deletedBy");
    openapiFields.add("deletedDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("galacticId");
    openapiRequiredFields.add("entityId");
    openapiRequiredFields.add("univSpecificId");
    openapiRequiredFields.add("createdBy");
    openapiRequiredFields.add("createdDate");
    openapiRequiredFields.add("updatedBy");
    openapiRequiredFields.add("updatedDate");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PepProfileEntities
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PepProfileEntities.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PepProfileEntities is not found in the empty JSON string", PepProfileEntities.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PepProfileEntities.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PepProfileEntities` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PepProfileEntities.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("galacticId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `galacticId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("galacticId").toString()));
      }
      if (!jsonObj.get("univSpecificId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `univSpecificId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("univSpecificId").toString()));
      }
      if ((jsonObj.get("isTrueMatch") != null && !jsonObj.get("isTrueMatch").isJsonNull()) && !jsonObj.get("isTrueMatch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isTrueMatch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isTrueMatch").toString()));
      }
      if ((jsonObj.get("isCaseClosed") != null && !jsonObj.get("isCaseClosed").isJsonNull()) && !jsonObj.get("isCaseClosed").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isCaseClosed` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isCaseClosed").toString()));
      }
      if ((jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull()) && !jsonObj.get("comments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comments").toString()));
      }
      if (!jsonObj.get("createdBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdBy").toString()));
      }
      if (!jsonObj.get("updatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedBy").toString()));
      }
      if ((jsonObj.get("deletedBy") != null && !jsonObj.get("deletedBy").isJsonNull()) && !jsonObj.get("deletedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deletedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deletedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PepProfileEntities.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PepProfileEntities' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PepProfileEntities> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PepProfileEntities.class));

       return (TypeAdapter<T>) new TypeAdapter<PepProfileEntities>() {
           @Override
           public void write(JsonWriter out, PepProfileEntities value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PepProfileEntities read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PepProfileEntities given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PepProfileEntities
  * @throws IOException if the JSON string is invalid with respect to PepProfileEntities
  */
  public static PepProfileEntities fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PepProfileEntities.class);
  }

 /**
  * Convert an instance of PepProfileEntities to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

