/*
 * ucd_pmgmt_v1_api
 * Swagger documentation for UCD Profile Management Service API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: UCDWSDevTeam@westernunion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wu.brwallet.customer.profile.model.common.ucd.profilemanagement;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import com.wu.brwallet.customer.profile.model.common.ucd.profilemanagement.ReceiverNameExisting;
import com.wu.brwallet.customer.profile.model.common.ucd.profilemanagement.ReceiverNameNew;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.wu.brwallet.customer.profile.model.common.ucd.profilemanagement.JSON;

/**
 * Receiver Name Model Schema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T21:22:09.739306500+05:30[Asia/Calcutta]")
public class ReceiverName {
  public static final String SERIALIZED_NAME_EXISTING = "existing";
  @SerializedName(SERIALIZED_NAME_EXISTING)
  private ReceiverNameExisting existing;

  public static final String SERIALIZED_NAME_NEW = "new";
  @SerializedName(SERIALIZED_NAME_NEW)
  private ReceiverNameNew _new;

  public ReceiverName() {
  }

  public ReceiverName existing(ReceiverNameExisting existing) {
    
    this.existing = existing;
    return this;
  }

   /**
   * Get existing
   * @return existing
  **/
  @javax.annotation.Nullable
  public ReceiverNameExisting getExisting() {
    return existing;
  }


  public void setExisting(ReceiverNameExisting existing) {
    this.existing = existing;
  }


  public ReceiverName _new(ReceiverNameNew _new) {
    
    this._new = _new;
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @javax.annotation.Nullable
  public ReceiverNameNew getNew() {
    return _new;
  }


  public void setNew(ReceiverNameNew _new) {
    this._new = _new;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiverName receiverName = (ReceiverName) o;
    return Objects.equals(this.existing, receiverName.existing) &&
        Objects.equals(this._new, receiverName._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(existing, _new);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiverName {\n");
    sb.append("    existing: ").append(toIndentedString(existing)).append("\n");
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("existing");
    openapiFields.add("new");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReceiverName
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReceiverName.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReceiverName is not found in the empty JSON string", ReceiverName.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ReceiverName.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReceiverName` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `existing`
      if (jsonObj.get("existing") != null && !jsonObj.get("existing").isJsonNull()) {
        ReceiverNameExisting.validateJsonObject(jsonObj.getAsJsonObject("existing"));
      }
      // validate the optional field `new`
      if (jsonObj.get("new") != null && !jsonObj.get("new").isJsonNull()) {
        ReceiverNameNew.validateJsonObject(jsonObj.getAsJsonObject("new"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReceiverName.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReceiverName' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReceiverName> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReceiverName.class));

       return (TypeAdapter<T>) new TypeAdapter<ReceiverName>() {
           @Override
           public void write(JsonWriter out, ReceiverName value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReceiverName read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReceiverName given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReceiverName
  * @throws IOException if the JSON string is invalid with respect to ReceiverName
  */
  public static ReceiverName fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReceiverName.class);
  }

 /**
  * Convert an instance of ReceiverName to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

